//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNViMeSimbolo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eslogan
    {
        public int Id { get; set; }
        public Nullable<int> Team { get; set; }
        public Nullable<System.DateTime> Hour { get; set; }
        public string WordChooses { get; set; }
    }
}
