//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNViMeSimbolo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UnvimeEscudoEntities : DbContext
    {
        public UnvimeEscudoEntities()
            : base("name=UnvimeEscudoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Eslogan> Eslogan { get; set; }
    
        public virtual ObjectResult<GetCountTopAzul_Result> GetCountTopAzul()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountTopAzul_Result>("GetCountTopAzul");
        }
    
        public virtual ObjectResult<GetCountTopCeleste_Result> GetCountTopCeleste()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountTopCeleste_Result>("GetCountTopCeleste");
        }
    
        public virtual ObjectResult<GetCountTopFiveEslogans_Result> GetCountTopFiveEslogans()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountTopFiveEslogans_Result>("GetCountTopFiveEslogans");
        }
    
        public virtual ObjectResult<GetCountTopNaranja_Result> GetCountTopNaranja()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountTopNaranja_Result>("GetCountTopNaranja");
        }
    
        public virtual ObjectResult<GetCountTopVerde_Result> GetCountTopVerde()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountTopVerde_Result>("GetCountTopVerde");
        }
    
        public virtual ObjectResult<GetAllCountsForTeam_Result> GetAllCountsForTeam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCountsForTeam_Result>("GetAllCountsForTeam");
        }
    
        public virtual ObjectResult<GetAllWords_Result> GetAllWords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllWords_Result>("GetAllWords");
        }
    }
}
